---
weight: 6
title: Low Pressure
author: "Lenny Lin"
categories: [Troubleshooting Logbook]
tags: []
toc: true
draft: true
date: "2022-11-09"
lastmod: "2022-11-09"
---


<!--more-->

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(collapse = TRUE)
```

```{r, warning = F, include=F}
library(SixSigma)
library(qcc)

#font = c(1, 2, 3), values for the font to use. The values refer, in order, to branches, causes and effect.
# 1: normal, 2: bold, 3: italic
#cex = c(1, 0.8, 1)) # cex, values for the graphical character expansion. The values refer, in order, to branches, causes and effect
# they are the size.
```





```{r template, echo= F }
effect <- "Low Pressure"
causes.gr <- c("Leaks", "Partially obstructed solvent inlet filter")
causes <- vector(mode = "list", length = length(causes.gr))
causes[1] <- list(c("1", "2"))
causes[2] <- list(c("a", "b"))
causes[3] <- list(c("A", "B"))
causes[4] <- list(c("10", "20"))
ss.ceDiag(effect, causes.gr, causes, main = "Low Pressure", sub = "",
          ss.col = c("#8ad472", "#8ad472", "#8ad472", "#8ad472","#8ad472"))
```


```{r SixSigma package, echo= F }
effect <- "Low Pressure"
causes.gr <- c("Leaks", "Inlet Filter")
causes <- vector(mode = "list", length = length(causes.gr))
causes[1] <- list(c("---Connection: Tubing to valve", "---Connection: Tubing to column"))
causes[2] <- list(c("---Partially obstructed solvent inlet filter"))
ss.ceDiag(effect, causes.gr, causes, main = "Low Pressure", sub = "",
          ss.col = c("#8ad472", "#8ad472", "#8ad472", "#8ad472","#8ad472"))
```


## QCC package


```{r qcc package, echo = F }
cause.and.effect(cause=list("ESI" = c("---ESI probe adjustment"),
                            "MS/MS Health Check" = c("---EMV", "---Mass resolution", paste("---Ion source manitenance", "\n i.e. new capillary electrode")),
                            "Method" = c("---Calibration curve"),
                            "System Suitability Test" = c(paste("---Monitoring", "\n i.e. Peak area, Pressure trace", "\n  XIC overlays")),
                            "Sample Prep" = c("---Lost in Elute", "---Review"),
                            "Human Errors" = c("---Repeat run", "---Re-injection", paste("---Check & Replacement","\n i.e. mobile phases, parts")),
                            "Infusion Analysis - MS/MS" = c("---Analyte-to-Internal Standard Ratio", "---Qualifier-to-Quantifier Ratio")
                            ),
                 effect=paste("Low", "\nSensitivity"),
                 title = "Low Sensitivity with LC-MS/MS",
                 font = c(1, 3, 2), 
                 cex = c(0.7, 0.6, .9))
```


